### ISSUE TITLE
有计划加入doc/docx等格式支持吗？

### ISSUE THREAD

**Issue by SaraKale** [denny0258/Chinese_Convert#1]
无意间看到的项目，真没想到会有人开发opencc的简易版，我自己安装opencc不成功就放弃了……
试用了下做的好棒！目前测试txt、html都可以转换，但doc文档类是无法转换吗？
想知道该项目目前支持哪种格式，感谢您开发了优秀项目！

**Comment by DennySORA** [comment]
目前的話還未提供，但之後有可能會加入，並且把GUI跟機器學習後的字詞修正加入。

**Comment by DennySORA** [comment]
@SaraKale 我之後放出原始碼，可以自行安裝中間插件或修改。
